### ISSUE TITLE
As an Open Forest admin, I would like to see the most updated architecture diagram so that I can understand the current flow.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [18F/fs-intake-module#1511]
## Notes
The architecture for Open Forest needs to be updated on the wiki.

## Acceptance Criteria
- [x] The Open Forest architecture diagram is updated on the wiki

## Tasks
- [x] Add the new Open Forest architecture diagram to the wiki code
- [x] Change the diagram currently on the architecture wiki page to the updated diagram
- [ ] PO approved

## Definition of Done
- [x] The new Open Forest architecture diagram is easily accessible on the wiki

**Comment by Rebekah-Hernandez** [comment]
https://github.com/USDAForestService/fs-open-forest/wiki/Ongoing-site-architecture the image has been updated

**Comment by mwreiss** [comment]
Looks good!  Validation completed.
