### ISSUE TITLE
As an Open Forest developer I would like a standard "beautifier" to be chosen and implemented so that our code-base is consistently styled

### ISSUE THREAD

**Issue by Dmac26** [18F/fs-intake-module#1516]
## Tasks
- [x] Find several code beautifiers and present them to the team
- [ ] Once beautifier is selected implement it on local instance of Open Forest
- [ ] Run all pages through the chosen beautifier
- [ ] Correct any issues that are found
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
