### ISSUE TITLE
As an Special Uses Admin I would like test applications deleted from the database

### ISSUE THREAD

**Issue by Dmac26** [18F/fs-intake-module#1517]
## Notes
Multiple test applications are still being held in the Special Uses database. Since we no longer need them we should delete them to free up more space on the server.

![CancelledToBeDeleted.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/cfb61f4b-804d-447f-aa1b-9957b9afe6cc)

![RejectedToBeDeleted.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/0b7db0dc-6c6c-4721-b5a9-4a9356d2e320)
## Tasks
- [x] Catalog all of the test applications that need to be deleted in a list below
- [x] Deleted unneeded applications
- [x] After apps have been deleted double-check the Special-Uses website for any extra applications that should have been deleted
- [ ] PO approved

## Applications (By ID) to be deleted
- [] 9 not needed.
- [x] 21
- [x] 23
- [x] 24
- [x] 47
- [x] 48
- [x] 49
- [x] 50
- [x] 51
- [x] 52
- [x] 54
- [x] 55

**Comment by Dmac26** [comment]
@mwreiss - Hey Matt, you mentioned on the stand-up today that everything that is going to be deleted from SUDS needs to be cataloged on a cart. Does the above suffice or do we need a separate card for every application that is to be deleted?

**Comment by mwreiss** [comment]
One issue is good to cover them all.  Thanks!

**Comment by abdul-fs** [comment]
@mwreiss We need to enable production to connect to database and clean the permits.

**Comment by mwreiss** [comment]
@abdul-fs sounds good, thanks

**Comment by abdul-fs** [comment]
This test permits have been completed. @Dmac26 Please verify

**Comment by Dmac26** [comment]
@abdul-fs  - Verified, with the exception of one (application # 9) which we left in the "expired table" for now.
