### ISSUE TITLE
RESEARCH: Permits/Authorizations Candidates for Open Forest Platform 

### ISSUE THREAD

**Issue by carlsonem** [18F/fs-intake-module#1526]
## Background

To help support executives in the long-term vision of the Open Forest platform, research is needed to analyze which permits and authorizations services by the National Forest would be good candidates for the Open Forest platform.

## Acceptance Criteria
- [x] We have an understanding of the USFS landscape of all CFO associated permits and authorization services.
- [x] We have an understanding of all relevant permits and authorizations offered within different sectors in USFS.
- [x] We have an understanding of available platform capabilities and merits for permit/authorizations recommendations.
- [x] We have a systematic understanding of USFS permit and authorizations properties for platform evaluation.

## Tasks
- [x] Add appropriate tasks.
- [x] Add acceptance criteria.
#### Phrase 1
- [x] Determine if this story needs to be converted to epic.
- [x] Create and published research plan.
- [x] Identify all USFS permits and authorizations services (interviews).
     - [x] Meeting with PO
     - [x] Meeting with CFO
     - [x]  Meeting with department POCs
- [x] Curate and develop a matrix identifying the properties of each permit or authorizations.

#### Phrase 2
- [x] Conduct competitive analysis of platforms:
     - [x] Develop a feature table Open Forest Platform (strengthens and weakens).
     - [x] Develop a feature table Recreation.gov (strengthens and weakens).
     - [x] Develop a feature table third option (strengthens and weakens).
- [x] Synthesize a matrix evaluating permit/authorizations user needs versus properties of the platform.
- [x] Provide recommendations base on research.

## Definition of Done
- [x] All tasks are completed successfully and approved as noted
- [x] Research is published to wiki.
- [x] Findings are shared with the team.
- [ ] PO Approved

**Comment by aQuib** [comment]
[Here is the research plan](https://usfs.app.box.com/notes/763345678941)

**Comment by aQuib** [comment]
[Here is matrix](https://usfs.app.box.com/file/769172311109)
