### ISSUE TITLE
permit number duplicates in firewood

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-intake-module#1530]
## Notes
* Our pay.gov permits are being rejected due to permit number duplicates inside our node server, they're re-using sequences off of christmas trees *

## Acceptance Criteria
- [x] permit numbers for firewood follow a different sequence from christmas trees

## Tasks
- [x] change zpad paramaters or sequence start for firewood

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by Dmac26** [comment]
The numbers look good. Moving to "Awaiting Acceptance"
