### ISSUE TITLE
Investigate and decide best path for calling completeCollection 

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-intake-module#1545]
## Notes
* We are currently not initiating completeCollection for pay.gov integration within firewood *

## Acceptance Criteria
- [ ] completeCollection is called after purchasing a firewood permit
- [ ] completeCollection is successfully completed

## Tasks
- [ ] Investigate best method for initiating completeCollection for pay.gov interface
- [ ] Investigate using completeCollection on the route params
- [ ] Investigate implementing completeCollection by bypassing to call directly after a successful startCollection

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mwreiss** [comment]
Implemented and verified based on pay.gov testing.  @mtlaney can you verify this good to be closed out?
