### ISSUE TITLE
Update pay.gov ssl certs in Staging and Production.

### ISSUE THREAD

**Issue by abdul-fs** [18F/fs-intake-module#1555]
## Notes
* What are things we should consider when making this story *
 This story is to update ssl certs for pay.gov in staging and production. The current QA certs expires on Jan26, 2021 and prod expires on Jan1, 2021.

## Tasks
- [x] Get the pfx key from pay.gov
- [x] Generate the key using openssl command
- [x] Update in QA 
- [x] Update in Prod 
- [ ] Validate
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by bboddiger** [comment]
@mwreiss Approved.  Thank you.

**Comment by abdul-fs** [comment]
Thanks Team. This is completed.
