### ISSUE TITLE
Update and/or Develop Pipeline Documentation

### ISSUE THREAD

**Issue by carlsonem** [18F/fs-intake-module#1556]
## Notes
Update documentation for the Open Forest Pipeline

## Acceptance Criteria
- [x] All documentation for pipeline are documented

## Tasks

- [x] Certificate updates:
- Overview (who you get certs from, where they go on the platform), list of certs and expiration
- Screenshots
- cf commands

- [x] Adding API's ie. Splunk, NRM-TIM, SUDS, Pay.gov (Middle-layer):
- Overview
- Document
- Screenshots
- cf commands

- [x] Maintaining and Adding API's (Middle-layer):
- Overview
- Document
- Screenshots
- cf commands

- [x] Platform Configuration (open-forest-platform):
- Overview
- Document
- Screenshots
- cf commands

- [x] Platform General Maintenance:
- Overview
- Document
- Screenshots

- [x] SIA Release Process-what do you do in your role:
- Overview
- Screenshots
- What documents, Issues and Releases get created/updated

- [x] Enabling/Disabling SSH:
- Overview
- Document
- Screenshots
- cf commands

- [x] Manually re-initiating Splunk Logs:
- Overview
- Document
- Screenshots
- cf commands

- [x] Configuration of Environment Variables:
- Overview
- Document
- Screenshots
- cf commands

**Comment by carlsonem** [comment]
@abdul-fs please make this issue a priority. Please provide all documentation in a word document for starters.

**Comment by mwreiss** [comment]
@Rebekah-Hernandez This is what Abdul put together.  [Pipeline Documentation.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/5804259/Pipeline.Documentation.docx)

**Comment by Rebekah-Hernandez** [comment]
@mwreiss  Here is the updated document. Please look over and make sure everything is correct.

[Development Pipeline Documentation 1556.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/5845043/Development.Pipeline.Documentation.1556.docx)

**Comment by Rebekah-Hernandez** [comment]
Here is the wiki page on the internal wiki: https://code.fs.usda.gov/forest-service/Open-Forest-Program/wiki/Development-Pipeline-Documentation
