### ISSUE TITLE
custom fields for POSS not integrating after pay.gov

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-intake-module#1562]
## Notes
* POSS team isn't receiving custom collection field from pay.gov on the new fuelwood permits. This is due to a missmatch in possId vs possFinancialId in the forest model. It will need to be changed to match current possFinancialId *

## Acceptance Criteria
- [ ] forests.js migration is updated to match possFinancialId
- [ ] fs-forests model is updated to match possFinancialId
- [ ] poss team is able to verify custom collection fields

## Tasks
- [ ] forests.js migration is updated to match possFinancialId
- [ ] fs-forests model is updated to match possFinancialId
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
