### ISSUE TITLE
pay.gov card declined failure

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-intake-module#1573]
## Notes
* Our pay.gov card system is failing for our dummy card. I'm assuming our period expired*

![Screen Shot 2021-02-03 at 12.35.59 PM.png](https://images.zenhubusercontent.com/5b8860cc4b5806bc2be51669/962e48f9-bba6-4ca0-9682-f400ba2118e7)

## Acceptance Criteria
- [ ] research why our 411111------ etc card is being declined from pay.gov
- [ ] update on our end or pay.gov end 

## Tasks
- [ ] update card to approve and send 200 request
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
@mtlaney please confirm this is still working

**Comment by carlsonem** [comment]
OBE fixed by GSA
