### ISSUE TITLE
As an Open Forest User I'd like to know that there is a time-out that will render my application null and void if left to sit without saving

### ISSUE THREAD

**Issue by Dmac26** [18F/fs-intake-module#1575]
## Notes
Currently there is no warning to users that there is a time-out function set for Open Forest users. This means that after a period of time a users input data that has not yet been submitted and is lost. Unfortunately there is also not error thrown when a user clicks "submit" after the time limit has already been exceeded. All they know is that their application isn't being submitted and they assume it's a problem with our site.

Therefore, it would be beneficial to have a warning, error message, a save feature, or some combination of the three.

## Tasks
- [ ] Discuss and determine the best approach for remediation
- [ ] After a remediation approach is decided on, layout the steps to complete here in the task-list
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by Rebekah-Hernandez** [comment]
Here is the first round of mockups. I included wording that can be used now and then also a draft for if a Save Progress feature is implemented @Dmac26 

![1557_1](https://user-images.githubusercontent.com/56045852/108251365-e500f400-711c-11eb-8b84-d217be01faf2.png)

![1557_2](https://user-images.githubusercontent.com/56045852/108251377-ea5e3e80-711c-11eb-8abf-759007cbbe15.png)

![1557_3](https://user-images.githubusercontent.com/56045852/108251394-efbb8900-711c-11eb-8f57-87002bc192ac.png)
