### ISSUE TITLE
Containerize Application

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-intake-module#1590]
## Notes
* In order to pursue our move to AWS, we are looking to containerize the application to deploy via Kubernetes *

## Acceptance Criteria
- [ ] Frontend is containerized
- [ ] Backend is containerized
- [ ] Docker compose will have them talk to eachother

## Tasks
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
