### ISSUE TITLE
Setup containerized application to read VCAP variables for PROD

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-intake-module#1592]
## Notes
* After application is successfully containerized, we need to implement vcap variables to successfully differentiate between local, dev, staging, and prod *

## Acceptance Criteria
- [ ] dockerfiles build off of VCAP variables

## Tasks
- [ ] update dockerfiles, update vcap variables
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
