### ISSUE TITLE
Take Open Forest out of Production turn off Mount Baker Snoqualmie  Special Use Permits

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-intake-module#1595]
## Notes
This story is based on the desire of USFS Leadership form National Forest System and Chief Information Office to no longer utilize the Open Forest platform as a pilot service for special user permits on the Mount Baker Snoqualmie NF.  This task will also mitigate known issues associated with lack of product management staff.

## Acceptance Criteria
- [  ] The Open Forest System is not available in production for the public to apply for permits of any kind

## Tasks
- [x] Disable the Mount baker Snoqualmie NF DNS access to allow for permit applications on Friday 4/16 at approximately 12 EST (to allow MBS time to pull needed information)
- [ ] Post a message directing staff to the Mount Bake Snoqualmie Webpage for any Special Use Permit Needs https://www.fs.usda.gov/main/mbs/passes-permits/event-commercial 
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by aaronburk** [comment]
Please follow-up with Brandon Neighbors he will be in the product owner role if their are any questions Aaron Burk can provide support as needed.

**Comment by mwreiss** [comment]
@aaronburk with your approval we are decommissioning in the next 5min.  Do you approve?

**Comment by aaronburk** [comment]
See adjustment to decommission on 4/16 12 EST to accommodate MBS staff needs

**Comment by mwreiss** [comment]
Prod service has been disabled
![image](https://user-images.githubusercontent.com/50459930/115064205-48579a00-9eb2-11eb-8dd1-8795f18d02a9.png)
