### ISSUE TITLE
Refactor xmas tree svg to html (Spike?)

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-intake-module#344]
## Notes
originally used svg to have better print rendering but probably could refactor more simply to just html and then convert to pdf/png

## Acceptance Criteria
- [ ] have more consistent with the rules generation
- [ ] easier accessibility annotations
- [ ] more updatable
- [ ] greatly simplify reading in of template

## Tasks
- [ ] swap out Permit Design SVG with HTML and CSS
- [ ] include alt text/ aria annotations
- [ ] update applicant info and appForestSpecificInfo
- [ ] switch out from svg2png to dom-to-image in the generatePng
- [ ] separate out the rules functions into own service
- [ ] PO approved.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by adborden** [comment]
@lauraGgit this replaces https://github.com/18F/fs-open-forest-platform/issues/142 correct? I should pick this up?

**Comment by ASprinkle** [comment]
Not working on during live production

**Comment by lauraGgit** [comment]
We might want to consider pulling this back in - according to new relic, this part of the process takes 4.6 seconds on average.. which is in part thanks to the back and forth with pay.gov, but we might be able to look at ways to improve the performance by switching to HTML.

**Comment by lauraGgit** [comment]
3.9 seconds of that time being the permit generation, and sending the emails.

**Comment by lauraGgit** [comment]
Turns out that most of these are because of the bug identified in #483
