### ISSUE TITLE
As a developer I want to be able to test alt text using a valid screen reader for windows.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-intake-module#820]
## Notes
* What are things we should consider when making this story *
as a follow up to #780 We need a valid screen reader for windows in order to test that the alt text is readable. If alt text is present, pa11y testing says that alt text is present and we are accepting that for now.

## Acceptance Criteria
- [ ] We have a valid screen reader for windows in order to test that alt text is readable on Open Forest.

## Tasks
- [x] Confirm that we need a valid screen reader (necessary redundancy for pa11y testing)
- [x] Research how to get a valid screen reader
- [ ] Get a valid screen reader
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by aQuib** [comment]
Research is needed to determine if Amp is a viable screen reader for Open Forest.

**Comment by aQuib** [comment]
Research is needed to evaluate NVDA as a valid screen reader.
